Repository Jaydee94/kubeseal-webgui, pull requests merged in 2020-10, with the labels that each got.

#25 Add VueJS Badge to README
  README.md
Labels: enhancement, hacktoberfest-accepted

#26 Create Github Action
  .github/workflows/main.yml
Labels: hacktoberfest-accepted

#27 Refactor Dockerfiles
  Dockerfile-API
  Dockerfile-UI
Labels: hacktoberfest-accepted

#28 Add new gif as demo to README
  README.md
  demo/kubseal-demo-2.0.0.gif
Labels: hacktoberfest-accepted

#29 OpenShift Support for the ui
  .github/workflows/main.yml
  Dockerfile-UI
  Dockerfile.api
  Dockerfile.ui
  api/Dockerfile
  chart/kubeseal-webgui/templates/deployment.yaml
  chart/kubeseal-webgui/templates/route-api.yaml
  chart/kubeseal-webgui/templates/route-ui.yaml
  chart/kubeseal-webgui/templates/service.yaml
  ui/Dockerfile
Labels: bug, hacktoberfest-accepted

#30 hotfix: changed log level of request content to debug
  api/app/kubeseal.py
Labels: bug, hacktoberfest-accepted

#32 Fixed service port mapping
  chart/kubeseal-webgui/templates/deployment.yaml
  chart/kubeseal-webgui/templates/service.yaml
Labels: bug, hacktoberfest-accepted
